### ISSUE TITLE
core.Zip assumes that comment field in "End of Central Directory" record has size 0

### ISSUE THREAD

**Issue by kossebau** [kogmbh/WebODF#548]
Code currently reads the record by just taking the last 22 bytes of the file:
`runtime.read(url, filesize - 22, 22, function (err, data) {`
But the size of the record is dynamic, depends on the value in the ".ZIP file comment length" (see APPNOTE.txt).

Annoying thing here is that to find the start of the record when parsing from the end can be fooled by the issue that the end of central dir signature could appear in the comment (and possibly elsewhere), as nothing is forbidding this. So any code might be rather guess work, trying to find the first range of bytes where all the data makes sense for the record...

Possibly not an issue with most real-life ODF files. Just noting here now that it was discovered, to free my head of it :)

**Comment by peitschie** [comment]
Fixed in #910
