### ISSUE TITLE
Unable to build on Mavericks due to qt5 dependencies

### ISSUE THREAD

**Issue by vielmetti** [kogmbh/WebODF#890]
Also noted in detail here:

https://github.com/kogmbh/ViewerJS/issues/142

I'm trying to build on OS X 10.9 Mavericks using a qt5 provided by Homebrew.  I updated the docs with this pull request

https://github.com/kogmbh/WebODF/pull/889

to reflect the updated version of qt5 provided by Homebrew (5.4.1 instead of 5.2.1). This part of it did work, however, I'm not clear how to get ViewerJS to do the right thing.

**Comment by kossebau** [comment]
Given #899 applied meanwhole and this issue not adding anything to https://github.com/kogmbh/ViewerJS/issues/142 I will close this issue here again, to avoid double bookkeeping.
