### ISSUE TITLE
"Fill the blanks" with parameters

### ISSUE THREAD

**Issue by brauliobo** [kogmbh/WebODF#914]
Is is possible to set some parameters spaces (for example, NAME, ADDRESS, etc) inside the document and then via some method tell webodf to fill those parameters with data from an external application/database?

Thanks!

**Comment by adityab** [comment]
WebODF won't talk to an external database, but I suppose you could stuff some custom placeholder elements inside the ODF document. And then when the document is rendered in the browser, simply use the DOM API/jQuery/* to query those elements and replace with the desired values.

Hope that helps!

**Comment by brauliobo** [comment]
@adityab perfect, I think this is enough! Will try it later.

**Comment by brauliobo** [comment]
@adityab I've tried the demo and couldn't find on the interface a way to put placeholder elements. Should I do it directly on the ODT's XML webodf generates?

**Comment by adityab** [comment]
Yeah I'm afraid you have to write your own DOM manipulation js there (or unzip the file, and hand-edit the XML to add placeholders). Keep in mind that these elements are namespaced, so you'll have to use the appropriate `createElementNS`-like methods. Elements which aren't correctly namespaced will be filtered out of the XML when you save.

**Comment by brauliobo** [comment]
@adityab The "Generate documents" at http://webodf.org/demos seems to be just what I wanted, trying to understand how it works

**Comment by brauliobo** [comment]
the demo seems not be working, it never finish loading: http://webodf.org/demos/invoice-generator/#invoice.fodt
