### ISSUE TITLE
How to set page size for wodoeditor?

### ISSUE THREAD

**Issue by hnategh** [kogmbh/WebODF#933]
Hi there,

I am integrating wodoeditor in our project and when I create an empty A4 document with LibreOffice and try to edit it with wodoeditor I get a pretty small paper size not an A4 paper (this is reproducible in webodf editor demo page as well). I am wondering if there's a way to set a page size, e.g. A4 with wodoeditor, or a work around to show a full size paper.

Thank you in advance!

Regards,
Hadi

**Comment by vandenoever** [comment]
WodoEditor does not show the pages when editing. The width should be correct, but the height depends only on the amount of text. When you load the edited document in LibreOffice again, you'll see how the page layout it. Like all aspects of the file you read, WodoEditor will keep them the same unless you explicitly edit them.

Even if a dialog is added to set paper size, this will only affect the width of the column that user can see.

It is recommended to add a preview button that integrates with e.g. LibreOffice to create a PDF to give the user accurate layout feedback.

**Comment by hnategh** [comment]
Definitely, helped me to fix my issue regarding the paper size. Thanks a lot!

**Comment by vandenoever** [comment]
Glad to hear it.
