### ISSUE TITLE
My docx file is not loading using webodf.js

### ISSUE THREAD

**Issue by hiteshbal91** [kogmbh/WebODF#939]
Hi Team,

I need to implement online doc editor on one of my project, I searched a lot after going through the multiple plugins I decided to go with the webodf plugin.

But I am facing an issue of loading my .docx file on editor so not able to see anything on my server.
My code is simple as given like load webodf file and load it's canvas nothing much(as given in the getting started).

I seek help from here. I have seen an earlier issue about compression but I am using the apache2 server where gzip is not enabled.

Please let me know if you need further information.

**Comment by peitschie** [comment]
Hi @hiteshbal91 

WebODF is only designed to read ODT/ODF documents (Open Document Format). docx is the Microsoft OpenXML format, and is a completely different type of document.

You'll need to convert the docx to an odt file using Microsoft Word or LibreOffice.

More detail about these document differences can be found at https://support.office.com/en-us/article/Differences-between-the-OpenDocument-Text-odt-format-and-the-Word-docx-format-d9d51a92-56d1-4794-8b68-5efb57aebfdc.

I've closed this issue as there are no plans that I'm aware of for supporting docx.
